GET localhost:7777/api/game/admin/view


###


POST localhost:7777/api/game/admin/reset


###
POST localhost:7777/api/game/player/command
token: PybGunlX
Content-Type: application/json

{"@type":"MoveCommand","direction":"RIGHT"}


###
POST localhost:7777/api/game/player?name=Jurek
